spring.application.name=ecom-user-be
server.port=8081

# CORS
cors.allowed-origin=${CORS_ALLOWED_ORIGIN:http://localhost:3000}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ecom_user_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:imuPostgre@123}

# JPA
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Actuator
management.endpoints.web.base-path=/management
management.endpoints.web.exposure.include=health,info,metrics,env,beans,mappings,loggers
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always
management.info.env.enabled=true
management.info.java.enabled=true
management.info.os.enabled=true

# App info shown at /actuator/info
info.app.name=ecom-user-backend
info.app.version=0.0.1-SNAPSHOT
info.app.description=E-Commerce Backend REST API

